# Generated by Django 3.2.16 on 2023-01-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='traceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, default='', max_length=20)),
                ('operator', models.CharField(blank=True, max_length=20, null=True)),
                ('team_leader', models.CharField(blank=True, max_length=20, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=20, null=True)),
                ('machine', models.CharField(blank=True, max_length=20, null=True)),
                ('operation', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
