# Generated by Django 3.2.19 on 2023-06-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shell_no', models.CharField(blank=True, max_length=3, null=True)),
                ('cast_code', models.CharField(blank=True, max_length=3, null=True)),
                ('heat_code', models.CharField(blank=True, max_length=3, null=True)),
                ('shell_serial_no', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=5, null=True)),
                ('added', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'ScannerData',
                'verbose_name_plural': 'ScannerDataPoints',
                'ordering': ('updated_at',),
            },
        ),
    ]
