# Generated by Django 3.2.19 on 2023-06-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0002_scannerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannerdata',
            name='shell_serial_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
