# Generated by Django 3.2.19 on 2023-05-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagedetection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serial_detection',
            old_name='file',
            new_name='media',
        ),
    ]
